#!/bin/bash
#
#  Ubuntu Mate 22.02 LTS
# last change: nie, 14 sie 2022, 15:08:31
#
cd /root/install
P=`basename $0`
DONE_FILE=done_${P}

if [ -f ${DONE_FILE} ]
then
    echo "Script ${P} already ran..."
    exit 1
fi

echo "Starting FREE-SERWER...."

echo "---[ teraz budujemy obraz systemu...  ]---"

ltsp dnsmasq -d1 --dns-server="208.67.222.222 208.67.220.220"
echo "czy działa dnsmasq? -- [enter lub ctrl+c]"
echo "--------------------------"
ps xfaw | grep dns
read KK
ltsp image /
echo "-[ENTER]-------------------------"
read KK
ltsp ipxe
ltsp nfs
ltsp initrd
ltsp info

echo "--------------------------"
echo "teraz reboot i test działania"
echo "--------------------------"

touch ${DONE_FILE}
