#!/bin/bash
#
echo " Installing other software"

# Delta Chat
# echo "Private messages - https://jurkiewicz.chat"
wget https://github.com/deltachat/deltachat-desktop/releases/download/v2.35.0/deltachat-desktop_2.35.0_amd64.deb
dpkg -i deltachat-desktop_2.35.0_amd64.deb


# Pinta graphic - compile
# apt install dotnet8 build-essential autotools-dev autoconf-archive gettext intltool libadwaita-1-dev webp-pixbuf-loader
# wget ...
# compile ....
