#!/bin/bash
#
# Ubuntu Mate 22.04.05 LTS
# last change: sob, 4 sty 2025, 20:35:06
#
# Ubuntu MATE 24.04.03 LTS
# last change: pią, 2 sty 2026, 09:39:50

# first, Microsoft Edit
cd /
wget https://jurkiewicz.tech/assets/_msedit.tgz
tar xzvf _msedit.tgz && rm -f _msedit.tgz 
#

cd /root/install
P=`basename $0`
DONE_FILE=done_${P}

if [ -f ${DONE_FILE} ]
then 
    echo "Script ${P} already ran..."
    exit 1
fi

echo "Starting FREE-SERWER...."

echo "cleaning APT and install main network ..."

pt update
apt purge snapd 
apt autoremove
apt install -y openssh-server net-tools curllibicu-dev

# add firefox PPA
add-apt-repository ppa:mozillateam/ppa
echo "Package: firefox*" > /etc/apt/preferences.d/mozillateamppa
echo "Pin: release o=LP-PPA-mozillateam" >> /etc/apt/preferences.d/mozillateamppa
echo "Pin-Priority: 501" >> /etc/apt/preferences.d/mozillateamppa

# brave browser
curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -
echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com stable main" >> /etc/apt/sources.list.d/brave.list

# MS-Edge and Google Chrome must be installed from deb files

apt update
apt install firefox-esr brave-browser  gstreamer1.0-pipewire libxdo3 -y

#rustdesk
wget https://github.com/rustdesk/rustdesk/releases/download/1.4.4/rustdesk-1.4.4-x86_64.deb
dpkg -i rustdesk-1.4.4-x86_64.deb
#
# wget https://github.com/rustdesk/rustdesk/releases/download/1.2.3-2/rustdesk-1.2.3-2-x86_64.deb
# dpkg -i rustdesk-1.2.3-2-x86_64.deb


echo "--------------------------"
echo "teraz reboot i ltsp_01_install"
echo "--------------------------"

touch ${DONE_FILE}
