#!/bin/bash
#
# Ubuntu Mate 22.02 LTS
# last change: nie, 14 sie 2022, 15:08:31
#
cd /root/install
P=`basename $0`
DONE_FILE=done_${P}

if [ -f ${DONE_FILE} ]
then 
    echo "Script ${P} already ran..."
    exit 1
fi

echo "Starting FREE-SERWER...."
export XAN="NO"

# clearing apt
echo "cleaning APT and install main network ..."
cat apt.sources.list > /etc/apt/sources.list
apt update
apt purge snapd
apt autoremove
apt install -y openssh-server net-tools curl

# add firefox PPA
add-apt-repository ppa:mozillateam/ppa
echo "Package: firefox*" > /etc/apt/preferences.d/mozillateamppa
echo "Pin: release o=LP-PPA-mozillateam" >> /etc/apt/preferences.d/mozillateamppa
echo "Pin-Priority: 501" >> /etc/apt/preferences.d/mozillateamppa

# brave browser
curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -
echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com stable main" >> /etc/apt/sources.list.d/brave.list

# MS-Edge
echo "deb [arch=amd64] http://packages.microsoft.com/repos/edge/ stable main" >> /etc/apt/sources.list.d/microsoft_edge.list

apt update
apt install firefox-esr brave-browser microsoft-edge-stable
apt list --upgradable

echo "Type YES to dist upgrade"
read KYES

if [ -z "${KYES}" ]
then
    KYES="NO"
fi


if [ ${KYES} == "YES" ]
then
    echo "dist upgrade ? (ENTER)"
    read KK
    apt dist-upgrade
    echo "Please reboot.... (ENTER)"
    echo "dist-upgrade done" > ${DONE_FILE}
    read KK
    reboot
fi

# XanModLinux
if [ ${XAN} == "YES" ] 
then

    apt install -y wget
    echo " installing xanmod kernel... press ENTER."
    read KK
    echo 'deb http://deb.xanmod.org releases main' | tee /etc/apt/sources.list.d/xanmod-kernel.list && wget -qO - https://dl.xanmod.org/gpg.key | apt-key add -
    apt update
    apt install linux-xanmod 
fi


echo "--------------------------"
echo "teraz reboot i ltsp_01_install"
echo "--------------------------"

touch ${DONE_FILE}
